name: Download ChromeDriver

on:
  push:
    branches:
      - main
      - with-junit
  workflow_dispatch:

jobs:
  download_chromedriver:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get latest Stable ChromeDriver URL (linux64)
        id: get_chromedriver_url
        run: |
          url=$(curl -s https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json | \
          jq -r '.channels.Stable.downloads.chromedriver[] | select(.platform=="linux64") | .url')
          echo "url=$url" >> $GITHUB_OUTPUT

      - name: Download ChromeDriver
        run: |
          wget ${{ steps.get_chromedriver_url.outputs.url }} -O chromedriver-linux64.zip

      - name: Unzip ChromeDriver
        run: unzip chromedriver-linux64.zip -d chromedriver

      - name: List ChromeDriver folder contents
        run: ls -l chromedriver


